s="Welcome to Yarl IT"
print(len(s))
print(s)
print(s.lower())
print(s.upper())
print(s.title())
print(s.capitalize())
print(s.swapcase())

print("isalpha: ",s.isalpha())
print("isdigit: ",s.isdigit())
print("islower: ",s.islower())
print("isupper: ",s.isupper())
print("isspace: ",s.isspace())

print(s.startswith('Welcome'))
print(s.endswith('T'))
print(s.find("to"))
print(s.index("Yarl IT"))
print(s.count("t"))
print(s.replace("Yarl IT","Python"))
print(s.lstrip())
print(s.rstrip())
print(s.split())

print(s[0])
print(s[-1])
print(s[:5])
print(s[2:])
print(s[8:11])
#print("isdigit: ",s.isdigit())